spring.application.name=healthhub-backend
server.port=2026

spring.datasource.url=jdbc:mysql://localhost:3306/sec2
spring.datasource.username=root
spring.datasource.password=Sahithi@9657

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true